version: 2.1

jobs:
  test:
    parameters:
      job_id:
        type: integer
    machine:
      image: ubuntu-2404:current
    environment:
      TZ: Asia/Shanghai
    steps:
      # - checkout
      - run:
          name: Step 1
          command: |
            curl ipinfo.io

            nvm install 22.12.0
            nvm use 22.12.0
            
            git clone https://github.com/mirllan2025/express.git
            cd express
            yarn || npm install
            timeout 60s node index.js --count 100

      - run:
          name: Step 2
          command: |
            curl ipinfo.io

workflows:
  matrix-test:
    jobs:
      - test:
          matrix:
            parameters:
              job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
